### ISSUE TITLE
remove `pseudo dependencies`

### ISSUE THREAD

**Issue by Flokkq** [Flokkq/ryvex#3]
Since ryvex is marketed as a ***dependency free*** text editor, there should be **zero** dependencies in Cargo.toml. But the trained eye can count **2** depencies 💢 💢 

```toml
[package]
name = "ryvex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3.3" # 1
libc = "0.2.154"  # 2
```

These depencies only exist because the author @Flokkq is too scared to use the dread ***unsafe*** keyword. Please fix your skill issues.
